server:
  port: ${CONSUMER_PORT:8002}

spring:
  application:
    name: image_resizer
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:9092
      group-id: group_id

topic:
  name:
    consumer:
      frame: frame.sender


auto:
  create:
    topics:
      enable: true


# Actuator property - performance impact
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always


